### ISSUE TITLE
No such file or directory: './annotations.json'

### ISSUE THREAD

**Issue by p-ranav** [YvanYin/DiverseDepth#17]
test_any_diversedepth.py [requires](https://github.com/YvanYin/DiverseDepth/blob/master/tools/test_any_diversedepth.py#L53) an `annotations.json` file. 

What is this file and can it be downloaded from somewhere for the pre-trained model?  

```console
Traceback (most recent call last):
  File "/Users/foobar/opt/anaconda3/envs/diversedepth/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/foobar/opt/anaconda3/envs/diversedepth/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/foobar/Documents/Projects/DiverseDepth/tools/test_any_diversedepth.py", line 55, in <module>
    f = open(anno_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: './annotations.json'
```

**Comment by YvanYin** [comment]
We have updated the testing code.
